spring:
  # MySQL DB 설정
  datasource:
      
    # Resd replica 구성
    master: # Write(Insert, Update, Delete)
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://kms-master.postgres.database.azure.com:5432/postgres?serverTimezone=UTC
#      jdbc-url: jdbc:postgresql://kn3-kbh-prd-ocareplus-hic-rdb-psd.postgres.database.azure.com:5432/postgres?serverTimezone=UTC
      read-only: false
      username: master
      password: megazone!234
      hikari:
      
    slave:  # Read(Select)
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://kms-slave1.postgres.database.azure.com:5432,kms-slave2.postgres.database.azure.com:5432/postgres?serverTimezone=UTC
#      jdbc-url: jdbc:postgresql://kn3-kbh-prd-ocareplus-hic-rdb-psd-rp1.postgres.database.azure.com:5432,kn3-kbh-prd-ocareplus-hic-rdb-psd-rp2.postgres.database.azure.com:5432/postgres?serverTimezone=UTC
      read-only: true # Slave DB는 Read만
      username: master
      password: megazone!234
      hikari:
      
#spring:
    
  mvc:
    view:
      prefix: /WEB-INF/views/   # Controller가 리턴시 앞에붙는 경로 명
      suffix: .jsp              # Controller가 리턴시 뒤에붙는 경로 명
  
  # 화면 자동반영 관련 설정
  devtools:
    livereload:
      enabled: true
      
# Mybatis 설정
mybatis:
  # default Package location - resultType의 Alias를 지정합니다.
  type-aliases-package: com.kbhc.blackcode.VO
  # mapper location - 바라 볼 xml 파일을 지정합니다.
  mapper-locations: classpath:mapper/*.xml
  # column name to camel case - 반환 받는 컬럼명을 CamelCase로 받는 설정을 합니다.
  configuration:
    map-underscore-to-camel-case: true
server:
  servlet:
    encoding:
      charset: UTF-8
      
logging:
  level:
    '[com.zaxxer.hikari]': DEBUG